DROP TABLE IF EXISTS MetaData;
DROP TABLE IF EXISTS PrimaryData;
DROP TABLE IF EXISTS SyncLog;
DROP TABLE IF EXISTS Battery;

CREATE TABLE "Battery" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"BusinessUnit"	TEXT NOT NULL,
	"EdgeHWRSN"	TEXT NOT NULL,
	"EdgeSWRVer"	TEXT NOT NULL,
	"BMSHWRSN"	TEXT NOT NULL UNIQUE,
	"BMSSWRVer"	TEXT NOT NULL
);

CREATE TABLE "MetaData" (
	"Key"	TEXT NOT NULL,
	"Value"	TEXT NOT NULL,
	"Unit"	TEXT
);

CREATE TABLE "PrimaryData" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Localtime"	TEXT NOT NULL,
	"ReqWCheck"	INTEGER NOT NULL,
	"ReqWoutCheck"	INTEGER NOT NULL,
	"ClearFault"	INTEGER NOT NULL,
	"EnBalance"	INTEGER NOT NULL,
	"DV"	INTEGER NOT NULL,
	"SOC"	INTEGER NOT NULL,
	"AError"	INTEGER NOT NULL,
	"AWarning"	INTEGER NOT NULL,
	"IChgLimit"	INTEGER NOT NULL,
	"IDsgLimit"	INTEGER NOT NULL,
	"SOH"	INTEGER NOT NULL,
	"VBattery"	INTEGER NOT NULL,
	"IBattery"	INTEGER NOT NULL,
	"VCellMin"	INTEGER NOT NULL,
	"VCellMinID"	INTEGER NOT NULL,
	"VCellMax"	INTEGER NOT NULL,
	"VCellMaxID"	INTEGER NOT NULL,
	"TModMin"	INTEGER NOT NULL,
	"HV2"	INTEGER NOT NULL,
	"TModMax"	INTEGER NOT NULL,
	"TModMinID"	INTEGER NOT NULL,
	"TModMaxId"	INTEGER NOT NULL,
	"ErrorFlags"	INTEGER NOT NULL,
	"WarningFlags"	INTEGER NOT NULL,
	"CreatedAt"	TEXT NOT NULL,
	"BatteryId"	INTEGER NOT NULL,
	FOREIGN KEY("BatteryId") REFERENCES "Battery"("Id")
);

CREATE TABLE "SyncLog" (
	"BatteryId"	INTEGER NOT NULL,
	"PrimaryDataId"	INTEGER NOT NULL,
	"SyncDate"	TEXT,
	"SyncComment"	TEXT,
	"Synced"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("BatteryId","PrimaryDataId")
);

INSERT INTO Battery  (BusinessUnit, EdgeHWRSN, EdgeSWRVer, BMSHWRSN, BMSSWRVer) VALUES ('eTransport', 'Ax_12598324', 'Ax_2.5.3',
'G2_2.4.1', 'G2_3.2.0');

INSERT INTO PrimaryData  (
    Localtime,
ReqWCheck,
ReqWoutCheck,
ClearFault,
EnBalance,
DV,
SOC,
AError,
AWarning,
IChgLimit,
IDsgLimit,
SOH,
VBattery,
IBattery,
VCellMin,
VCellMinID,
VCellMax,
VCellMaxID,
TModMin,
HV2,
TModMax,
TModMinID,
    TModMaxID,
ErrorFlags,
WarningFlags,
CreatedAt,
BatteryId
) VALUES (
    '13.05.2019 08:09:05',
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    date('now'),
    1    
),
(
    '14.06.2019 09:09:05',
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    date('now'),
    1    
),
(
    '15.07.2019 10:09:05',
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    date('now'),
    1    
);

INSERT INTO  SyncLog (BatteryId, PrimaryDataId) VALUES (1, 1);
INSERT INTO SyncLog (BatteryId, PrimaryDataId) VALUES (1, 2);
INSERT INTO SyncLog (BatteryId, PrimaryDataId) VALUES (1, 3);

INSERT INTO MetaData (Key, Value, UNIT) VALUES
('Localtime',	'Edge device local time', NULL),
('ReqWCheck',	'Connect Request with check', NULL),
('ReqWoutCheck',	'Connect Request without check', NULL),
('ClearFault',	'Clear Faults', NULL),
('EnBalance',	'Balance Enable', NULL),
('DV',	'Delta Voltage', '0.1V'),
('SOC',	'State of charge', '%'),
('AError',	'Active Error-Code', 'Bitfield'),
('AWarning',	'Active Warning-Code', 'Bitfield'),
('IChgLimit',	'Charge Current Limit', '0.1A'),
('IDsgLimit',	'Discharge Current Limit', '0.1A'),
('SOH',	'State of Health', '%'),
('VBattery',	'Battery voltage', '0.1V'),
('IBattery',	'Battery current', '0.1A'),
('VCellMin',	'Cell Voltage Min', 'mV'),
('VCellMinID',	'Cell Voltage Min ID', NULL),
('VCellMax',	'Cell Voltage Max', 'mV'),
('VCellMaxID',	'Cell Voltage Max ID', NULL),
('TModMin',	'Module Temp Min', '0.1°C'),
('HV2',	'Load Voltage', '0.1V'),
('TModMax',	'Module Temp Max', '0.1°C'),
('TModMinID',	'Module Temp Min ID', NULL),
('TModMaxID',	'Module Temp Max ID', NULL),
('ErrorFlags',	'Error Flags', NULL),
('WarningFlags',	'Warning Flags', NULL);

